server:
  port: 8890

spring:
  cloud:
    gateway:
      routes:
        - id: MS-Usuario
          uri: lb://MS-USUARIO
          predicates:
            - Path=/usuario/**
        - id: MS-Categoria
          uri: lb://MS-CATEGORIA
          predicates:
            - Path=/categoria/**
        - id: MS-Meme
          uri: lb://MS-MEME
          predicates:
            - Path=/meme/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  sleuth:
    sampler:
      probability: 1.0
    zipkin:
      base-url: http://localhost:9411
      sender:
        type: web

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
        base-path: /actuator
    restart:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.filter: DEBUG
    org.springframework.cloud.gateway.route: DEBUG
    org.springframework.cloud.gateway.handler: DEBUG
    com.netflix.discovery: WARN
  pattern:
    console:
      logFormat: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"