server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 3000

spring:
  sleuth:
    sampler:
      probability: 1.0
    zipkin:
      base-url: http://localhost:9411
      sender:
        type: web

management:
  endpoints:
    web:
      exposure:
        include: "*"
        base-path: /actuator
    restart:
      enabled: true

logging:
  level:
    root: INFO
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
  pattern:
    console:
      logFormat: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"