server:
  port: 8888

spring:
  application:
    name: Config-Server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/configs
  sleuth:
    sampler:
      probability: 1.0
    zipkin:
      base-url: http://localhost:9411
      sender:
        type: web

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
        base-path: /actuator
    restart:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework.cloud.config: DEBUG
    org.springframework: WARN
  pattern:
    console:
      logFormat: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"